spring.application.name=booking_hotel
server.port=8080
spring.datasource.url=jdbc:mysql://localhost:3306/hotel_booking_db?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true&createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=10092005Long

server.servlet.context-path=/api/v1

spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=50MB

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false

jwt.secret-key=404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
jwt.access-token-expiration=86400000
jwt.refresh-token-expiration=604800000


# MoMo Sandbox Credentials
momo.endpoint=https://test-payment.momo.vn/v2/gateway/api/create
momo.partner-code=MOMOBKUN20180529
momo.access-key=klm05TvNBzhg7h7j
momo.secret-key=at67qH6mk8w5Y1nAyMoYKMWACiEi2bsa
momo.redirect-url=http://localhost:8080/api/v1/payments/momo-return
momo.ipn-url=http://localhost:8080/api/v1/payments/momo-ipn
momo.request-type=payWithCC

# Spring Mail Configuration
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=phungvanlong10925@gmail.com
spring.mail.password=arjgydtgjqhrzblj
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# Google OAuth2 Client Configuration
spring.security.oauth2.client.registration.google.client-id=807553747109-i9f5jua0s4edftfmnk7dmlkekimuegi4.apps.googleusercontent.com
spring.security.oauth2.client.registration.google.client-secret=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
spring.security.oauth2.client.registration.google.scope=openid,profile,

app.otp.expiration=5

# Spring Data Redis
spring.data.redis.host=localhost
spring.data.redis.port=6379


gemini.api-key=AQ.Ab8RN6JlRSKb-wTbNZrz-fCbG7MWotlhX_CddDxkGiybMTQVPw
gemini.model=gemini-2.0-flash
gemini.temperature=0.7
gemini.max-output-tokens=2048